name: Build Infra-Prod

on:
  push:
    branches:
      - master
      - sandbox
      - 'environment/**'

jobs:
  build:
    runs-on: infrastructure-production-toolbox-ubuntu22-2g-1cpu-x64

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
