name: Checks

on:
  push:
    branches:
      - master
      - sandbox
      - 'environment/**'

jobs:
  build:
    runs-on: [foo, bar, biz]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
