name: Tests

on:
  push:
    branches:
      - master
      - sandbox
      - 'environment/**'

jobs:
  build:
    runs-on: infrastructure-production-toolbox-ubuntu22-4g-2cpu-x64

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
